### ISSUE TITLE
module 'pypdfium2' has no attribute 'FPDF_LoadDocument'

### ISSUE THREAD

**Issue by awied** [pypdfium2-team/pypdfium2#217]
I'm using version 4.8.0. 
How to reproduce:

import pypdfium2 as pdfium
doc = pdfium.FPDF_LoadDocument(THE_FILEPATH, None)

--> AttributeError: module 'pypdfium2' has no attribute 'FPDF_LoadDocument'

Observation: this works with version 3.21.1 but seems to be broken starting with version 4.0.0

**Comment by mara004** [comment]
Not broken. Deliberate change. Read the docs.

**Comment by mara004** [comment]
Quoting [changelog for v4](https://pypdfium2.readthedocs.io/en/latest/changelog.html#id9):
> The raw API is now isolated in a separate namespace (`pypdfium2.raw`). Moreover, the raw API bindings do not implicitly encode strings anymore (pypdfium2 is now built with a patched version of ctypesgen by default).

**Comment by mara004** [comment]
Your example could be rewritten like this
```python
import pypdfium2.raw as pdfium_c
doc = pdfium_c.FPDF_LoadDocument(str(THE_FILEPATH).encode("utf-8"), None)
```
However, I encourage using our helper class `PdfDocument` for document loading.

**Comment by mara004** [comment]
Oh, actually the Readme was highly unclear about this, I forgot to update. I'll push a commit shortly.
I prefer to work with RTD; keeping the Readme in sync has become a bit of a nuisance.
